DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.categories;
DROP TABLE IF EXISTS public.compilations CASCADE;


CREATE table IF NOT EXISTS public.users (
 user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(254) NOT NULL UNIQUE,
	username varchar(250) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (user_id),
	CONSTRAINT users_un UNIQUE (email)
);

CREATE table IF NOT EXISTS public.categories (
 category_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	category_name varchar(50) NOT NULL UNIQUE,
	CONSTRAINT categories_pk PRIMARY KEY (category_id),
	CONSTRAINT categories_un UNIQUE (category_name)
	ON DELETE RESTRICT
);

CREATE table IF NOT EXISTS public.compilations (
 compilation_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title varchar(50) NOT NULL UNIQUE,
	pinned boolean NOT NULL,
	-- events
	CONSTRAINT compilations_pk PRIMARY KEY (compilation_id)
	--CONSTRAINT compilations_fk
	ON DELETE CASCADE
);

CREATE table IF NOT EXISTS public.compilations_events(
 compilation_id bigint NOT NULL,
 event_id bigint NOT NULL,
 CONSTRAINT compilations_events_pk PRIMARY KEY (compilation_id, event_id)
);

