DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.compilations_events;
DROP TABLE IF EXISTS public.compilations CASCADE;
DROP TABLE IF EXISTS public.requests;
DROP TABLE IF EXISTS public.events;
DROP TABLE IF EXISTS public.categories RESTRICT;
DROP TABLE IF EXISTS public.locations;
DROP TABLE IF EXISTS public.subscribers_subscriptions;


CREATE table IF NOT EXISTS public.users (
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(254) NOT NULL UNIQUE,
	username varchar(250) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (user_id),
	CONSTRAINT users_un UNIQUE (email)
);

CREATE table IF NOT EXISTS public.categories (
    category_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	category_name varchar(50) NOT NULL UNIQUE,
	CONSTRAINT categories_pk PRIMARY KEY (category_id),
	CONSTRAINT categories_un UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS public.locations (
	lat float NOT NULL,
	lon float NOT NULL,
	CONSTRAINT locations_pk PRIMARY KEY (lat,lon)
);

CREATE table IF NOT EXISTS public.compilations (
 compilation_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title varchar(50) NOT NULL UNIQUE,
	pinned boolean NOT NULL,
	CONSTRAINT compilations_pk PRIMARY KEY (compilation_id),
	CONSTRAINT compilations_un UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS public.events (
	event_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	annotation varchar(2000) NOT NULL,
	category_id bigint NOT NULL,
	confirmed_requests int NOT NULL,
	created timestamp without time zone NOT NULL,
	description varchar(7000) NULL,
	event_date timestamp without time zone NOT NULL,
	initiator_id bigint NOT NULL,
	paid boolean NOT NULL,
	participant_limit int NOT NULL,
	published timestamp without time zone NULL,
	moderation boolean NOT NULL,
	state varchar(9) NOT NULL,
	title varchar(120) NOT NULL,
	lat float NOT NULL,
	lon float NOT NULL,
	CONSTRAINT events_pk PRIMARY KEY (event_id),
	CONSTRAINT events_un UNIQUE (title),
	CONSTRAINT events_categories_fk FOREIGN KEY (category_id) REFERENCES public.categories(category_id),
	CONSTRAINT events_users_fk FOREIGN KEY (initiator_id) REFERENCES public.users(user_id),
	CONSTRAINT events_locations_fk FOREIGN KEY (lat, lon) REFERENCES public.locations(lat,lon)
);


CREATE table IF NOT EXISTS public.compilations_events(
 compilation_id bigint NOT NULL,
 event_id bigint NOT NULL,
 CONSTRAINT compilations_events_pk PRIMARY KEY (compilation_id, event_id),
 CONSTRAINT compilations_events_compilations_fk FOREIGN KEY (compilation_id) REFERENCES public.compilations(compilation_id),
 CONSTRAINT compilations_events_events_fk FOREIGN KEY (event_id) REFERENCES public.events(event_id)
);

CREATE TABLE IF NOT EXISTS public.requests (
	request_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	event_id bigint NOT NULL,
	requester_id bigint NOT NULL,
	created timestamp without time zone NOT NULL,
	status varchar(9) NOT NULL,
	CONSTRAINT requests_pk PRIMARY KEY (request_id),
	CONSTRAINT requests_events_fk FOREIGN KEY (event_id) REFERENCES public.events(event_id),
	CONSTRAINT requests_users_fk FOREIGN KEY (requester_id) REFERENCES public.users(user_id)
);

CREATE table IF NOT EXISTS public.subscribers_subscriptions(
 user_id bigint NOT NULL,
 subscriber_id bigint NOT NULL,
 CONSTRAINT subscribers_pk PRIMARY KEY (user_id, subscriber_id),
 CONSTRAINT subscribers_fk FOREIGN KEY (subscriber_id) REFERENCES public.users(user_id),
 CONSTRAINT users_fk FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);

