DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.compilations;

CREATE table IF NOT EXISTS public.users (
 user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(254) NOT NULL UNIQUE,
	username varchar(250) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (user_id),
	CONSTRAINT users_un UNIQUE (email)
);

CREATE table IF NOT EXISTS public.compilations (
 compilation_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title varchar(50) NOT NULL UNIQUE,
	pinned boolean NOT NULL,
	-- events
	CONSTRAINT compilations_pk PRIMARY KEY (compilation_id)
	--CONSTRAINT compilations_fk
);